---
  - name: "Create yum repo /etc/yum.repos.d/{{ repo_ver }}.repo"
    yum_repository:
      name: "{{ repo_ver }}"
      description: MongoDB Repository
      baseurl: "{{ base_url }}"
      enabled: yes
      gpgcheck: yes
      gpgkey: "{{ gpg_key }}"
    # template:
    #   src: "{{ repo_ver }}.repo.j2"
    #   dest: "/etc/yum.repos.d/{{ repo_ver }}.repo"
    #   owner: root
    #   group: root
    #   mode: '0644'

  - name: "Template to override /etc/yum.conf"
    template:
      src: "yum.conf.j2"
      dest: "/etc/yum.conf"
      owner: root
      group: root
      mode: '0644'

  - name: "Install MongoDB packages"
    yum:
      name: "{{ packages }}"
      state: installed
    vars:
      packages: "{{ mdb_pkgs }}"
