---
  - name: "Template to create /etc/yum.repos.d/{{ repo_ver }}.repo"
    template:
      src: "{{ repo_ver }}.repo.j2"
      dest: "/etc/yum.repos.d/{{ repo_ver }}.repo"
      owner: root
      group: root
      mode: '0644'
