---
  - name: Shell Examples
    hosts: all
    tasks:

    - name: Check Date with Shell command
      shell:
         "date"
      register: datecmd
      tags: datecmd

    - debug: msg="{{datecmd.stdout}}"

    - name: check file that does exist with state file
      file:
        path: /tmp/test_file
        state: touch
